export const queryKeys = {
    sessions: ['sessions'] as const,
    session: (sessionId: string) => ['session', sessionId] as const,
    messages: (sessionId: string) => ['messages', sessionId] as const,
    sessionShares: (sessionId: string) => ['session-shares', sessionId] as const,
    machines: ['machines'] as const,
    machineCodexModels: (machineId: string) => ['machine-codex-models', machineId] as const,
    gitStatus: (sessionId: string) => ['git-status', sessionId] as const,
    sessionFiles: (sessionId: string, query: string) => ['session-files', sessionId, query] as const,
    sessionDirectory: (sessionId: string, path: string) => ['session-directory', sessionId, path] as const,
    sessionFile: (sessionId: string, path: string) => ['session-file', sessionId, path] as const,
    gitFileDiff: (sessionId: string, path: string, staged?: boolean) => [
        'git-file-diff',
        sessionId,
        path,
        staged ? 'staged' : 'unstaged'
    ] as const,
    slashCommands: (sessionId: string) => ['slash-commands', sessionId] as const,
    sessionCodexModels: (sessionId: string) => ['session-codex-models', sessionId] as const,
    sessionOpencodeModels: (sessionId: string) => ['session-opencode-models', sessionId] as const,
    machineOpencodeModelsForCwd: (machineId: string, cwd: string) => ['machine-opencode-models', machineId, cwd] as const,
    skills: (sessionId: string) => ['skills', sessionId] as const,
    projectToolCounts: (projectsKey: string) => ['project-tool-counts', projectsKey] as const,
    projectTools: (machineId: string, projectPath: string, kind: 'agent' | 'cron') => ['project-tools', machineId, projectPath, kind] as const,
    projectPortMappings: (machineId: string, projectPath: string) => ['project-port-mappings', machineId, projectPath] as const,
    cronRuns: (machineId: string, projectPath: string, cronId?: string | null) => ['cron-runs', machineId, projectPath, cronId ?? 'all'] as const,
}
